import { prisma } from '@/lib/db';
import Link from 'next/link';

/**
 * Backoffice Email Templates Listing Page.
 */
export default async function EmailTemplatesPage() {
  const templates = await prisma.emailTemplate.findMany({
    orderBy: { name: 'asc' },
  });

  return (
    <div className="space-y-10">
      <header>
        <h1 className="text-3xl font-bold text-gray-900 font-serif">Email Templates</h1>
        <p className="text-gray-600 mt-2">Manage the content and design of automated system emails.</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {templates.map((template) => (
          <div key={template.id} className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden flex flex-col">
            <div className="p-6 flex-grow">
              <div className="flex justify-between items-start mb-4">
                <span className="px-2 py-1 bg-gray-100 text-gray-600 text-[10px] font-bold uppercase tracking-widest rounded">
                  {template.slug}
                </span>
              </div>
              <h3 className="text-lg font-bold text-gray-900 mb-2">{template.name}</h3>
              <p className="text-sm text-gray-500 italic mb-4 line-clamp-1">Subject: {template.subject}</p>
            </div>
            <div className="p-4 bg-gray-50 border-t border-gray-200">
              <Link 
                href={`/backoffice/communications/templates/${template.id}`}
                className="block text-center text-sm font-bold text-[var(--color-primary-blue)] hover:text-blue-800 transition-colors"
              >
                Edit Design & Content
              </Link>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-blue-50 border border-blue-100 p-6 rounded-xl flex gap-4">
        <span className="text-2xl">⚡</span>
        <div className="text-sm text-blue-800">
          <p className="font-bold mb-1">Placeholder Support</p>
          <p>You can use <code>{"{{actionUrl}}"}</code> in templates to insert dynamic links for verification and password resets. These are automatically generated by the system.</p>
        </div>
      </div>
    </div>
  );
}
